# Generated by Django 4.1.2 on 2022-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('categoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('cargo', models.CharField(max_length=24)),
            ],
        ),
    ]
